"""empty message

Revision ID: 004017031a61
Revises: 
Create Date: 2021-10-10 20:59:04.364118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004017031a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('isdn_num', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('libraries',
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_table('library_activities',
    sa.Column('library_activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('library_book_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_book_id'], ['library_books.library_book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('library_activity_id')
    )
    op.create_table('library_books',
    sa.Column('library_book_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('last_library_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['last_library_activity_id'], ['library_activities.library_activity_id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ),
    sa.PrimaryKeyConstraint('library_book_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('library_books')
    op.drop_table('library_activities')
    op.drop_table('libraries')
    op.drop_table('books')
    # ### end Alembic commands ###
